# Generated by Django 3.1.7 on 2021-03-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_software_technical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='parcentage',
            new_name='percentage',
        ),
        migrations.RenameField(
            model_name='technical',
            old_name='parcentage',
            new_name='percentage',
        ),
    ]
